import { StyleSheet } from 'react-native';

export const detailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgb(245, 208, 208)',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  image: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
    backgroundColor: '#f5f5f5',
    borderRadius:100,
  },
  spriteHint: {
    fontSize: 12,
    color: '#999',
    textAlign: 'center',
    marginTop: 4,
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 8,
    color: '#333',
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    justifyContent: 'center',
  },
  tag: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    marginHorizontal: 4,
    marginBottom: 4,
  },
  tagText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  section: {
    backgroundColor: '#fff',
    marginVertical: 8,
    marginHorizontal: 12,
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  sectionArrow: {
    fontSize: 16,
    color: '#666',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  label: {
    fontSize: 14,
    color: '#666',
  },
  value: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },

  // Stats
  statsContainer: {
    marginTop: 4,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statLabel: {
    width: 110,
    fontSize: 13,
    color: '#555',
    fontWeight: '500',
  },
  statBarContainer: {
    flex: 1,
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    marginHorizontal: 8,
    overflow: 'hidden',
  },
  statBar: {
    height: '100%',
    borderRadius: 4,
  },
  statValue: {
    width: 35,
    fontSize: 13,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'right',
  },
  totalStatsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  totalStatsLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginRight: 12,
  },
  totalStatsValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#3b4cca',
  },

  // Habilidades
  abilityCard: {
    backgroundColor: '#f8f8f8',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#eee',
  },
  abilityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  abilityName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  abilityGeneration: {
    fontSize: 11,
    color: '#888',
  },
  abilityEffect: {
    fontSize: 13,
    color: '#555',
    lineHeight: 18,
  },
  moveCard: {
  backgroundColor: '#f8f8f8',
  padding: 12,
  borderRadius: 8,
  marginBottom: 8,
  borderWidth: 1,
  borderColor: '#eee',
},
moveHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 8,
},
moveName: {
  fontSize: 14,
  fontWeight: 'bold',
  color: '#333',
  flex: 1,
  marginRight: 8,
},
moveTypeContainer: {
  flexDirection: 'row',
  alignItems: 'center',
},
moveTypeTag: {
  paddingHorizontal: 10,
  paddingVertical: 2,
  borderRadius: 12,
  marginRight: 8,
},
moveTypeText: {
  color: '#fff',
  fontSize: 11,
  fontWeight: 'bold',
  textTransform: 'capitalize',
},
moveLevel: {
  fontSize: 12,
  color: '#666',
  fontWeight: '500',
},
moveStatsGrid: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  marginBottom: 8,
  gap: 6,
},
moveStatItem: {
  backgroundColor: '#fff',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 4,
  borderWidth: 1,
  borderColor: '#e0e0e0',
  flexDirection: 'row',
  alignItems: 'center',
  minWidth: 60,
},
moveStatLabel: {
  fontSize: 10,
  color: '#888',
  marginRight: 4,
  textTransform: 'uppercase',
},
moveStatValue: {
  fontSize: 12,
  fontWeight: 'bold',
  color: '#333',
},
moveEffect: {
  fontSize: 12,
  color: '#555',
  lineHeight: 16,
  marginTop: 4,
  paddingTop: 8,
  borderTopWidth: 1,
  borderTopColor: '#eee',
},
moveLoading: {
  fontSize: 12,
  color: '#999',
  fontStyle: 'italic',
  marginTop: 4,
},
moreMovesText: {
  fontSize: 12,
  color: '#666',
  textAlign: 'center',
  marginTop: 8,
  fontStyle: 'italic',
},
});